### ISSUE TITLE
Module 2 Assignment Work Documentation

### ISSUE THREAD

**Issue by jaakop** [Fisherman-s-Friends/Fisherman-s-Friends#40]
### Introduction:
Brief introduction, skill level, current know-how, your role in the project, also what you are responsible of.
### Completed tasks:
Show code/screenshots of functionalities you've created. Explain what the heck it does in text too. Show components, assets etc.
### In-progress tasks: 
Same as above. If you don't got any tasks in-progress, you can write, that you don't have anything etc.
### Emil
- [x] Introduction
- [x] Completed tasks
- [x] In-progress tasks 
### Aleksandar
- [x] Introduction
- [x] Completed tasks
- [x] In-progress tasks 
### Jaakko
- [x] Introduction
- [x] Completed tasks
- [x] In-progress tasks 
### Leevi
- [x] Introduction
- [x] Completed tasks
- [x] In-progress tasks 
## Afterwards comment them below

**Comment by jaakop** [comment]
# Introduction
Jaakko Sukuvaara - I've worked as a software developer with medical software in C# for 2.5 years. Before that I studied in vocational school to become a software developer. I've done video games as a hobby since 2015 and have done game jams in FGJ. 
My skill level for this course is advanced, I know C# and Unity very well. My role in the project has been programmer and project manager. I've developed game systems (Fish behaviors and world generation) and managed the project.
# Completed tasks
# In-progress tasks

**Comment by Emiliontti** [comment]
# Introduction
Emil Kola – A newcomer on the fields of game development. First time I touched Unity was when the entrance exams started. Made a small 2D game called Mow Them Down while doing the ex-ams. I’ve studied business information technology on vocational level, which focused mainly on C++ (12 years ago).
My skill level is probably somewhere between beginner-intermediate. I’ve programmed the input system in the game, as well as been responsible of the casting. Also coordinated a lot of the visual assets, as well as visual output. My role has been a programmer and a game designer.

# In-progress tasks
Next I'm trying to create and refine the gameplay loop, by tweaking the inputs (to allow mouse inputs) and also to continue making the gameplay more fun! This means collaboration with Alexandars and Jaakkos parts, making the underwater fishing line and making the inputs and minigame and catch system according this following concept:
![image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/143510738/7c35fe7d-8050-4bac-a72a-b503bd7e5581)

**Comment by Laffey-chan** [comment]
## Introduction

Leevi Kankainen
Somewhat new in game development field, but i have some experience with unity as an engine from personal small project's and from vocational school. i studies in vocational school in information and communication technology as c# programmer. For c# i have a done own project for automation stuff for me and quality of life programs for game information for me and some game modding if the game have been unity based.

I also have some skill in blender, but most of the information / knowlegde of blender i have forgotten because i haven't used blender for some time, but some basic i still have the knowlegde

My skill level is somewhere in intermidiate level.

What have i done this far for the game has been, For model's that we use to add bone's so we could animate the fishes and done the animation for the swim in unity animation and i have done the fish spawn for the game that the fishes spawn outside of the camera

## Task that i have done

Here is kinda more in dept what have i done if i have not documented in issues that what have i done.

### Fish Bone's

Because i have putten some images for the issue i will link the issue here and there you can see all the fishes and how the bones are on the fishes

[Adding bone's to the fishes · Issue #18 · Fisherman-s-Friends/Fisherman-s-Friends (github.com)](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/issues/18)

But For some documentation information i did not write at that time, But here is some information about this

The fish asset that we used didn't come with bone's / weight map, so somebody needed to add bone's to the fishes, so we could animate them better with the unity's own animation file / animator. So i added them to the fishes 

### Animation

Also here is kinda same that i putted images/gif to the issues i will link the issue where you can see the images/gif in action.

[Animate fish moving · Issue #15 · Fisherman-s-Friends/Fisherman-s-Friends (github.com)](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/issues/15)

But i didn't document some information what else i did for the animation, so i will put the information here.

The fish has 2 difrent animation for slow and fast swimming. I also edited the curve of the animation so the animation look's more smooth because it's looping so it''s not spiky and here is the image of the curve of one of the fishes, because allmost everyone have same kinda curve. 
![image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/25053472/b3f657c9-201e-4cf1-93f1-8508ec4f02cd)

**Comment by Emiliontti** [comment]
## A boat, a rod (and the open sea...) 
So, the first thing I started with the project, was to find suitable assets for the boat and the rod, and the bobber, to make the casting system and figuring out the gameplay loop. The rod and the boat were both free assets from the Unity asset store, and just needed a few tweaks to get them to fit:
![image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/143510738/f6caf43f-1688-494f-a4d0-aab5e94de030)

  
The rod is slightly scaled from the original model, but it looks way more fitting with the chunkier scale for the shaft. The boat was originally a bit more inhabited with boxes and a flagpole in the keel of the boat. I went and removed those to make some room for the rod.  
![image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/143510738/e151c1a2-2345-4145-a44d-4a568a022da1)

And here’s where the current setup is right now:  
![image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/143510738/0f1bc7c8-fd3e-413e-8763-e6e298b8646b)

Then I proceeded to add a bobber object to act as the point that flies into the water, when the player gives input to cast the line:
![image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/143510738/65d3a0a9-2596-4c19-a025-467fbf959478)

 
I also added a LineRenderer component (more on that in the next sections) from the rod to be created to the bobber, and from the bobber to the hook as well:
![image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/143510738/69b68998-1637-4795-ac93-8f6803da1351)

 
## Input Action Mapping and the Controls system

So, I was in charge of making the controls for the game. I looked into the old input system, but a 2nd year student recommended, that Unity’s new input system could be worth looking into as well, so I figured I’d try it out.  The input system is downloaded through the package manager and is installed for the project:
![image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/143510738/0614adef-7c2f-41c8-be56-5e51e06db164)

 
I went through a few simple steps to set the system up, first I made the action map for keyboard controls, and later I implemented mouse action too to work in unison with the casting (so you could either use keyboard and mouse, or either/or):
 
![image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/143510738/80b74a9e-f489-4ffa-ae65-73e5a935fcbe)


As of documenting, there’s keys to Cast the line with the CastLine action, and keys to Reset the line with the ResetCast keys. The HookActions mapping is a WIP, but it includes a different action map which changes the actions to do different stuff. This I saw useful, because when the line is cast, and the hook is generated you needed different actions, but you could still utilize the same keybinds to do stuff.
![image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/143510738/73c731f8-05de-43a0-8681-9e410631e460)

 
The calling of the actions is done inside the GameController object, that inhabits different controller scripts for the game. I added the Player Controller script and also the Player Input -component to the object:
![image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/143510738/093cfbe4-b6ec-4493-9815-b15fed368150)

 
 
The PlayerController script holds the input system for the game. First it defines the variables needed in the script: 
![image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/143510738/12729004-8cf5-4a49-a904-40d0e9753c70)

 
In the Start() function it stores the bobbers position; it gets component for the cast bar -slider component(will be talked about more in next chapter) and the hooks rigid body. 
![image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/143510738/bac3f36b-9e23-4e4b-aed2-704d18a30440)

 
There are currently 4 methods inside the class. 3 that control the casting system, and one IENumerator method, that is intended to pass information to the UI system for the cast bar.
 
The first Method, StartCast, is called based on the player using the input system (events):
![image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/143510738/4f1674f2-c038-4e26-b222-fd8a09afa02d)

 
The method checks if the player has casted, and conditions whether space key is pressed. It stores the start time of the key down; it sets the cast bar slider component active on the screen and starts the coroutine for the cast (for the GUI cast bar). 
On the .canceled if-statement it checks when the space-key is released. It stores the time from that moment and does a calculation for the velocity of the bobber and launches the bobber in that direction. The holdTotal variable makes sure, that the player cannot launch the bobber out of the screen. Also, it hides the cast bar and puts the haveYouCasted -variable in a false value, so that the player can cast again (if this is true, it means the bobber is in the air, and player cannot cast midair)
 
The next method ResetCast, is triggered when the player hits the ResetCast keys defined in the input action mapping.
![image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/143510738/04f9687d-f1bd-4a6e-9ac4-3dfd4431e586)

 
It first checks if the bobber is staying still and if it is, you can cast again. If it’s still moving, you cannot cast (stated by the Debug.Log). The “bobberScript.DestroyHookAndSwapActionMap();” syntax calls a method from the BobberScript.cs. Which has the following method:
![image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/143510738/c89630d4-dca0-4409-9721-38334f76531b)

  
The BobberScript.cs has a collision method, that compares when the bobber object hits the water surface:
 
![image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/143510738/819ba7f9-516b-4a32-ab0c-6e4f15764d85)
![image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/143510738/a5653ad0-396e-452f-a5a7-68ce0e8e9d70)


 

That includes the instantation of the  hook object (Aleksandars part), but for my work, it also has the action map switch. The logic behind this is, that when the bobber hits the water surface, the keybinds can partially stay the same, but the functionalities change.
![image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/143510738/70786f30-a9bf-4926-83e5-418ef6e695c6)

 
The logic is that when the cast is reseted in the PlayerController, the method is called, the bobber and the cast is reset, and the hook generated is destroyed. It changes the action maps (the controls) back to initial state.
The 3rd method is a WIP, meant to have functionality, when the player has casted the bobber, the bobber the water plane and the hook is generated, then the hook starts to fall. The idea is that this method is called when the player presses the StopHook -keys, that would make the hook stop falling at a certain depth. But as seen from the screenshot, it’s still in progress:

![image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/143510738/43e1aba0-d2d7-4098-824b-58f88e0b8899)

 
The IEnumerator method SliderChargeUp() is called to do a while loop, which is then updated to the visual GUI, to let the player see, how long he has held the cast key and how far the cast will approximately end. This is purely visual though and doesn’t affect the other system mentioned above.
![image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/143510738/09babec4-9c0a-464e-a1d5-6b27881f1f05)


## Canvas and cast bar
I created the Canvas for graphical elements on the hierarchy. This was needed in order to have visual representation of the cast bar. 
![image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/143510738/a9b5a0af-e44f-4fef-86c0-1a5ac9e7f536)

 
The canvas itself was setup to have screen space – overlay render mode, and to scale with reference resolution of Full HD(1080p). So, in the case of user being able to scale the game window, the elements would also rescale accordingly.
![image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/143510738/810454be-41dd-4cb0-8c54-c64a09476a14)

 
The canvas also holds the Slider, that was mentioned in the IEnumerator and PlayerController methods a few times. This is a slider object on the hierarchy, and it looks like this on the screen:

![image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/143510738/05fd51c1-f758-4cfb-9221-8a8a9e1a89ab)
![image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/143510738/7b0bfc2d-4dc9-4da2-8960-14c2aeb7b4fd)



The sliders activate state is deactive by default. This means, that using the code shown previously, the slider will only show when the space key is pressed. The time calculation is sent from the code to the value of the slider, which increases the longer you hold the space key:
![image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/143510738/2a44cbbd-7e79-4543-a427-73d68ef985b5)


 
## LineRender for the fishing line

The visual fishing lines are actually made with the LineRenderer component. 
![image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/143510738/8bfb8782-b00f-4c89-a985-5eabbbb893ef)

  
The actual logic is modified inside three different classes, which the LineController is base class, and HookLine and BobberLine inherit from this class. The logic is that the LineController does the calculations for the LineRenderer length and position. And the two other classes define the starting and ending points of the line. 
 
![image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/143510738/6a16321c-3409-4a12-bf84-ed2d1761e43a)

The logic between HookLine and BobberLine had to be different. BobberLine gets the start and endpoints from the inspector references and stores them in the array for the SetUpLine method (in LineController) to use.
![image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/143510738/618f2ae4-4706-415a-ab74-0572a78fba8b)

 
The previous method however couldn’t work with the line from the Bobber to the Hook because the hook is not initially in the scene-view and is instantiated from a prefab. So, this was a problem, because the reference couldn’t be made in advance, so that inspector couldn’t be utilized for this.
 
I did the following to solve this:

 
![image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/143510738/72d9d0f6-9994-4808-b020-50a220869646)


In the HookLine script the start position (so where the bobber is and where the hook starts falling from) is gotten by getting the “Bobber” named GameObject from the hierarchy (yes, only once because of the resource-heavy Find-function), and then stored in the variable. This way we get a reference for the start of the line and the endpoint is the hooks own Transform values.

## My issues from our Github (as of writing this document):
 
![image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/143510738/91e3681b-c78a-415f-a38e-f80e89ddf012)

**Comment by TemkaUwU** [comment]
### Introduction

Aleksandar Hristov – I am a fresh high school graduate with extremely limited unity experience mostly as an artist. I studied C# in high school but never learned to use it in the real world. My role in the project is very minor and I have been doing small bits of code wherever I can.  

### Completed tasks 

I made the hook object spawn and go down by modifying the bobber script 

![image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/143510355/0de23d0d-b20a-4e23-aea0-c0f1d5d880e5)

![image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/143510355/a2f34c53-f55c-41ce-9df8-32bb7d92fbea)


### In-Progress tasks 

    Stopping the hook from going out of bounds 

    Setting the hook into position 

    Reeling back the rod on command 

    Creating music and SFX for the game 

    (optional) Creating assets to replace the unity store ones

**Comment by jaakop** [comment]
Assignment 2 is submitted. Closing this issue.
